
name: Build And Test Shoppig List 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install modules
      run: npm install
    - name: Start unit tests
      run: npm run test:unit
    - name: Dispaly Softuni username
      run: echo "viktorybg"
  deploy-exam:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Exam prep
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_EXAM_KEY }}
        api-key: ${{ secrets.RENDER_API_KEY }}